export const CONTACT_EMAIL = "pmalaguistaoasis@gmail.com";
export const HOME_ROUTE_HASH = "#inicio";
export const PERSONAL_ROUTE_HASH = "#area-personal";
export const SIGNUP_ROUTE_HASH = "#area-personal-registro";
export const EVENTS_ROUTE_HASH = "#eventos";
export const SHOP_ROUTE_HASH = "#tienda";
export const PRIVACY_ROUTE_HASH = "#privacidad";
export const DATA_PROTECTION_LAW_URL =
  "https://www.boe.es/buscar/act.php?id=BOE-A-2018-16673";
export const GDPR_URL =
  "https://eur-lex.europa.eu/eli/reg/2016/679/oj?locale=es";
